# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUpload:
    def setup_method(self, method):
        self.driver = webdriver.Chrome('Driver/')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_upload(self):
        # Test name: upload
        # Step # | name | target | value
        # 1 | open | /upload |
        self.driver.get("https://www.namasha.com/upload")
        # 2 | setWindowSize | 564x708 |
        self.driver.set_window_size(564, 708)
        # 3 | click | id=tablistItem2 |
        self.driver.find_element(By.ID, "tablistItem2").click()
        # 4 | click | name=tVideoUrl |
        self.driver.find_element(By.NAME, "tVideoUrl").click()
        # 5 | type | name=tVideoUrl | https://www.namasha.com/videos/dl/7394578709-1080p/%D9%81%DB%8C%D9%84%D9%85-%D8%B4%D9%85%D8%A7-%D9%85%D8%B1%D8%AF%D9%85-%D8%A8%D8%A7-%D8%B2%DB%8C%D8%B1%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-You-People-2023-1080p.mp4
        self.driver.find_element(By.NAME, "tVideoUrl").send_keys(
            "https://www.namasha.com/videos/dl/7394578709-1080p/%D9%81%DB%8C%D9%84%D9%85-%D8%B4%D9%85%D8%A7-%D9%85%D8%B1%D8%AF%D9%85-%D8%A8%D8%A7-%D8%B2%DB%8C%D8%B1%D9%86%D9%88%DB%8C%D8%B3-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-You-People-2023-1080p.mp4")
        # 6 | click | id=startUrlUpload |
        self.driver.find_element(By.ID, "startUrlUpload").click()
        # 7 | click | css=.ng-invalid |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-invalid").click()
        # 8 | type | css=.ng-valid-maxlength | عنوان
        self.driver.find_element(By.CSS_SELECTOR, ".ng-valid-maxlength").send_keys("عنوان")
        # 9 | click | css=.post-category > .ng-pristine |
        self.driver.find_element(By.CSS_SELECTOR, ".post-category > .ng-pristine").click()
        # 10 | select | css=.post-category > .ng-untouched | label=فیلم و سینما
        dropdown = self.driver.find_element(By.CSS_SELECTOR, ".post-category > .ng-untouched")
        dropdown.find_element(By.XPATH, "//option[. = 'فیلم و سینما']").click()
        # 11 | click | css=.bf > .ng-pristine |
        self.driver.find_element(By.CSS_SELECTOR, ".bf > .ng-pristine").click()
        # 12 | type | css=.ng-valid-parse:nth-child(1) | توضیحات فیلم
        self.driver.find_element(By.CSS_SELECTOR, ".ng-valid-parse:nth-child(1)").send_keys("توضیحات فیلم")
        # 13 | click | css=.number-pb-num |
        self.driver.find_element(By.CSS_SELECTOR, ".number-pb-num").click()
        # 14 | click | css=.\_fit |
        self.driver.find_element(By.CSS_SELECTOR, ".\\_fit").click()
        # 15 | click | css=.ng-binding |
        self.driver.find_element(By.CSS_SELECTOR, ".ng-binding").click()
        # 16 | click | css=.co-m12 > p |
        self.driver.find_element(By.CSS_SELECTOR, ".co-m12 > p").click()
        # 17 | close |  |
        self.driver.close()


class TestSaveurl:
    def setup_method(self, method):
        self.driver = webdriver.Chrome('Driver/chromedriver109.exe')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_saveurl(self):
        # Test name: save_url
        # Step # | name | target | value
        # 1 | open | /TinTama |
        self.driver.get("https://www.namasha.com/TinTama")
        # 2 | setWindowSize | 564x708 |
        self.driver.set_window_size(564, 708)
        # 3 | click | id=load-more-btn |
        self.driver.find_element(By.ID, "load-more-btn").click()
        # 4 | runScript | window.scrollTo(0,13364) |
        self.driver.execute_script("window.scrollTo(0,13364)")
        # 5 | click | css=.list-row |
        self.driver.find_element(By.CSS_SELECTOR, ".list-row").click()
        # 6 | click | linkText=فیلم جدید ران اشتباه رفته دوبله فارسی / Ron's Gone Wrong 2021 |
        self.driver.find_element(By.LINK_TEXT, "فیلم جدید ران اشتباه رفته دوبله فارسی / Ron\'s Gone Wrong 2021").click()
        # 7 | click | css=.jw-video |
        self.driver.find_element(By.CSS_SELECTOR, ".jw-video").click()
        # 8 | close |  |
        self.driver.close()


def main():
    # ============================== export url video
    self = TestSaveurl()
    self.setup_method()



