# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSaveurl():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_saveurl(self):
    # Test name: save_url
    # Step # | name | target | value
    # 1 | open | /TinTama | 
    self.driver.get("https://www.namasha.com/TinTama")
    # 2 | setWindowSize | 564x708 | 
    self.driver.set_window_size(564, 708)
    # 3 | click | id=load-more-btn | 
    self.driver.find_element(By.ID, "load-more-btn").click()
    # 4 | runScript | window.scrollTo(0,13364) | 
    self.driver.execute_script("window.scrollTo(0,13364)")
    # 5 | click | css=.list-row | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-row").click()
    # 6 | click | linkText=فیلم جدید ران اشتباه رفته دوبله فارسی / Ron's Gone Wrong 2021 | 
    self.driver.find_element(By.LINK_TEXT, "فیلم جدید ران اشتباه رفته دوبله فارسی / Ron\'s Gone Wrong 2021").click()
    # 7 | click | css=.jw-video | 
    self.driver.find_element(By.CSS_SELECTOR, ".jw-video").click()
    # 8 | close |  | 
    self.driver.close()
  
